version: "3.2"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - tmp-data:/myapp/tmp
    environment:
      TZ: Asia/Tokyo
    command: dockerize -wait tcp://database:3306 -timeout 20s unicorn -c config/unicorn.rb
    tty: true
    stdin_open: true
    depends_on:
      - database

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3001:3000
    volumes:
      - ./front/:/home/node/app
    tty: true
    stdin_open: true
    depends_on:
      - api

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - tmp-data:/myapp/tmp
      - ./front/:/var/www
    depends_on:
      - front

  database:
    restart: always
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

volumes:
  bundle:
  tmp-data:
  mysql-datavolume:
    driver: local
