version: "3.2"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    environment:
      TZ: Asia/Tokyo
    ports:
      - 4000:3000
    command: tail -f /dev/null
    tty: true
    stdin_open: true
    depends_on:
      - database

  database:
    restart: always
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

volumes:
  bundle:
  mysql-datavolume:
    driver: local
