name: "Run jest, eslint"
on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./front

      - name: Run jest
        run: npm run test
        working-directory: ./front

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./front

      - name: Run eslint
        run: npm run lint
        working-directory: ./front
